import TalentEnitity from "../../entities/TalentEntity";

const TALENTS = [
    [{
        id: 1,
        name: "Overall Attack",
        description: ["Increases the ATK of your Legions's unit by ", " ."],
        buffValue: ["0%", "0.4%", "0.8%", "1.2%"],
        preview: "ATK bonus",
        level: 0,
        maxLevel: 3,
        group: 0,
        position: 0,
        isPrimaryCore: false,
        isSecondaryCore: false
    }]
]

export interface Talent {
    id: number,
    group: number,
    position: number,
    currentLevel: number,
    maxLevel: number,
    isPrimaryCore: boolean,
    isSecondaryCore: boolean
}

export const FOUNDATION_TALENT_CORES:Talent[][] = [
    [{
        id: 1,
        group: 0,
        position: 0,
        currentLevel: 0,
        maxLevel: 3,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 2,
        group: 0,
        position: 1,
        currentLevel: 0,
        maxLevel: 3,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 3,
        group: 0,
        position: 1,
        currentLevel: 0,
        maxLevel: 3,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 4,
        group: 0,
        position: 2,
        currentLevel: 0,
        maxLevel: 3,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 5,
        group: 0,
        position: 2,
        currentLevel: 0,
        maxLevel: 3,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 6,
        group: 0,
        position: 2,
        currentLevel: 0,
        maxLevel: 3,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 7,
        group: 1,
        position: 0,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: true,
        isSecondaryCore: false
    }], [{
        id: 8,
        group: 2,
        position: 0,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 9,
        group: 2,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 10,
        group: 2,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 11,
        group: 2,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 12,
        group: 2,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 13,
        group: 2,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 14,
        group: 2,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 15,
        group: 2,
        position: 3,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }, {
        id: 16,
        group: 2,
        position: 3,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }], [{
        id: 17,
        group: 2,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 18,
        group: 2,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 19,
        group: 2,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 20,
        group: 2,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 21,
        group: 2,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 22,
        group: 2,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 23,
        group: 2,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 24,
        group: 2,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 25,
        group: 2,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 26,
        group: 2,
        position: 7,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }, {
        id: 27,
        group: 2,
        position: 7,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }], [{
        id: 28,
        group: 3,
        position: 0,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 29,
        group: 3,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 30,
        group: 3,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 31,
        group: 3,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 32,
        group: 3,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 33,
        group: 3,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 34,
        group: 3,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 35,
        group: 3,
        position: 3,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }, {
        id: 36,
        group: 3,
        position: 3,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }], [{
        id: 37,
        group: 3,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 38,
        group: 3,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 39,
        group: 3,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 40,
        group: 3,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 41,
        group: 3,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 42,
        group: 3,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 43,
        group: 3,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 44,
        group: 3,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 45,
        group: 3,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 46,
        group: 3,
        position: 7,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }, {
        id: 47,
        group: 3,
        position: 7,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }], [{
        id: 48,
        group: 4,
        position: 0,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 49,
        group: 4,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 50,
        group: 4,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 51,
        group: 4,
        position: 1,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 52,
        group: 4,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 53,
        group: 4,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 54,
        group: 4,
        position: 2,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 55,
        group: 4,
        position: 3,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }, {
        id: 56,
        group: 4,
        position: 3,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }], [{
        id: 57,
        group: 4,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 58,
        group: 4,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 59,
        group: 4,
        position: 4,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 60,
        group: 4,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 61,
        group: 4,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 62,
        group: 4,
        position: 5,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 63,
        group: 4,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 64,
        group: 4,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }, {
        id: 65,
        group: 4,
        position: 6,
        currentLevel: 0,
        maxLevel: 5,
        isPrimaryCore: false,
        isSecondaryCore: false
    }], [{
        id: 66,
        group: 4,
        position: 7,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }, {
        id: 67,
        group: 4,
        position: 7,
        currentLevel: 0,
        maxLevel: 1,
        isPrimaryCore: false,
        isSecondaryCore: true
    }]
];

const TALENT_MAP = new Map<number, Talent>();
for (let i = 0; i < FOUNDATION_TALENT_CORES.length; i++) {
    for (let j = 0; j < FOUNDATION_TALENT_CORES[i].length; j++) {
        TALENT_MAP.set(FOUNDATION_TALENT_CORES[i][j].id, FOUNDATION_TALENT_CORES[i][j]);
    }
}


export default TALENT_MAP;